import { useState } from "react";
import { Download, ChevronDown, ChevronUp, Stethoscope } from "lucide-react";
import type { Prescription } from "../services/prescriptions";
import MedicineCard from "./MedicineCard";

interface Props {
  prescription: Prescription;
  showPatient?: boolean;
  showDownload?: boolean;
}

const AVATAR_FALLBACK = "https://api.dicebear.com/7.x/initials/svg?seed=";

function formatDate(iso: string) {
  return new Date(iso).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });
}

function buildPrintableHtml(px: Prescription): string {
  const medsRows = px.medicines.map(m => `
    <tr>
      <td style="padding:8px;border-bottom:1px solid #eee;">${m.name}</td>
      <td style="padding:8px;border-bottom:1px solid #eee;">${m.dosage}</td>
      <td style="padding:8px;border-bottom:1px solid #eee;">${m.frequency}</td>
      <td style="padding:8px;border-bottom:1px solid #eee;">${m.duration}</td>
      <td style="padding:8px;border-bottom:1px solid #eee;">${m.instructions || "—"}</td>
    </tr>
  `).join("");

  return `
    <!DOCTYPE html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>Prescription — ${formatDate(px.issued_at)}</title>
        <style>
          body { font-family: -apple-system, Helvetica, Arial, sans-serif; color: #1a1a1a; padding: 40px; max-width: 700px; margin: 0 auto; }
          h1 { font-size: 20px; margin-bottom: 4px; }
          .muted { color: #666; font-size: 13px; }
          .section { margin-top: 24px; }
          .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.05em; color: #888; margin-bottom: 6px; }
          table { width: 100%; border-collapse: collapse; margin-top: 8px; font-size: 13px; }
          th { text-align: left; padding: 8px; border-bottom: 2px solid #ddd; font-size: 11px; text-transform: uppercase; color: #888; }
          .footer { margin-top: 40px; font-size: 11px; color: #999; border-top: 1px solid #eee; padding-top: 12px; }
        </style>
      </head>
      <body>
        <h1>Medica — Prescription</h1>
        <p class="muted">Issued ${formatDate(px.issued_at)}</p>

        <div class="section">
          <p class="label">Prescribed by</p>
          <p>${px.doctor_name} — ${px.specialty}</p>
        </div>

        <div class="section">
          <p class="label">Patient</p>
          <p>${px.patient_name}${px.patient_age ? ` · ${px.patient_age} yrs` : ""}</p>
        </div>

        ${px.diagnosis ? `
        <div class="section">
          <p class="label">Diagnosis</p>
          <p>${px.diagnosis}</p>
        </div>` : ""}

        <div class="section">
          <p class="label">Medicines</p>
          <table>
            <thead>
              <tr><th>Name</th><th>Dosage</th><th>Frequency</th><th>Duration</th><th>Instructions</th></tr>
            </thead>
            <tbody>${medsRows}</tbody>
          </table>
        </div>

        ${px.notes ? `
        <div class="section">
          <p class="label">Doctor's notes</p>
          <p>${px.notes}</p>
        </div>` : ""}

        <div class="footer">
          This document was generated by Medica. Not valid without accompanying medical consultation records.
        </div>
      </body>
    </html>
  `;
}

function downloadPrescription(px: Prescription) {
  const html = buildPrintableHtml(px);
  const blob = new Blob([html], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `prescription-${formatDate(px.issued_at).replace(/,|\s/g, "-")}.html`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export default function PrescriptionCard({ prescription: px, showPatient, showDownload = true }: Props) {
  const [expanded, setExpanded] = useState(false);
  const dateLabel = formatDate(px.issued_at);
  const avatarSrc = px.doctor_avatar_url || `${AVATAR_FALLBACK}${encodeURIComponent(px.doctor_name)}`;

  return (
    <div className="bg-card rounded-xl border border-border hover:shadow-sm transition-all">
      <div className="p-5">
        <div className="flex items-start gap-4">
          <div className="w-11 h-11 rounded-xl overflow-hidden bg-muted flex-shrink-0">
            <img src={avatarSrc} alt={px.doctor_name} className="w-full h-full object-cover" />
          </div>
          <div className="flex-1 min-w-0">
            <div className="flex items-start justify-between gap-3 flex-wrap">
              <div>
                <p className="font-medium text-foreground">{px.doctor_name}</p>
                <p className="text-sm text-accent">{px.specialty}</p>
                {showPatient && (
                  <p className="text-xs text-muted-foreground mt-0.5">
                    Patient: {px.patient_name}{px.patient_age ? `, ${px.patient_age} yrs` : ""}
                  </p>
                )}
              </div>
              <div className="text-right flex-shrink-0">
                <p className="font-['DM_Mono',monospace] text-xs text-muted-foreground">{dateLabel}</p>
                <span className="text-xs bg-secondary text-secondary-foreground px-2 py-0.5 rounded-full mt-1 inline-block">
                  {px.medicines.length} medicine{px.medicines.length !== 1 ? "s" : ""}
                </span>
              </div>
            </div>
            {px.diagnosis && (
              <div className="mt-2 p-3 bg-muted/40 rounded-lg">
                <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-0.5">Diagnosis</p>
                <p className="text-sm text-foreground">{px.diagnosis}</p>
              </div>
            )}
          </div>
        </div>

        <div className="mt-3 flex items-center gap-2 flex-wrap">
          <button onClick={() => setExpanded(e => !e)} className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <Stethoscope className="w-3.5 h-3.5" />
            {expanded ? "Hide medicines" : "View medicines"}
            {expanded ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
          </button>
          {showDownload && (
            <button onClick={() => downloadPrescription(px)} className="flex items-center gap-1.5 text-sm text-accent hover:underline ml-auto">
              <Download className="w-3.5 h-3.5" /> Download
            </button>
          )}
        </div>
      </div>

      {expanded && (
        <div className="px-5 pb-5 border-t border-border pt-4 space-y-3">
          {px.medicines.map((med, i) => <MedicineCard key={med.id || i} med={med} index={i} />)}
          {px.notes && (
            <div className="bg-secondary rounded-xl p-4 mt-2">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide mb-1">Doctor's notes</p>
              <p className="text-sm text-muted-foreground leading-relaxed">{px.notes}</p>
            </div>
          )}
        </div>
      )}
    </div>
  );
}